import {
  $r,
  A,
  Fr,
  Ft,
  Gr,
  Ir,
  Jr,
  Nr,
  Pr,
  Qr,
  Rr,
  Ur,
  Vr,
  Vt,
  Wr,
  Z,
  ar,
  cr,
  dr,
  ir,
  oe,
  or,
  re,
  sr,
  zr
} from "./chunk-WIHGGV47.js";
import "./chunk-KA37DFDH.js";
export {
  Pr as TresCanvas,
  Z as catalogue,
  Qr as default,
  oe as extend,
  Rr as isProd,
  Ft as normalizeColor,
  Ir as normalizeVectorFlexibleParam,
  Wr as templateCompilerOptions,
  sr as trasverseObjects,
  Vt as useCamera,
  $r as useLoader,
  A as useLogger,
  ar as usePointerEventHandler,
  ir as useRaycaster,
  re as useRenderLoop,
  or as useRenderer,
  Vr as useSeek,
  Nr as useTexture,
  zr as useTres,
  dr as useTresContext,
  cr as useTresContextProvider,
  Gr as vAlwaysLookAt,
  Jr as vDistanceTo,
  Fr as vLightHelper,
  Ur as vLog
};
//# sourceMappingURL=@tresjs_core.js.map
